### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by thomasdavis** [EFForg/congress-forms-test#6]
```
{
error: "no implicit conversion of Symbol into String ["/home/congressforms/congress-forms/app/models/congress_member.rb:43:in `include?'", "/home/congressforms/congress-forms/app/models/congress_member.rb:43:in `rescue in fill_out_form'", "/home/congressforms/congress-forms/app/models/congress_member.rb:38:in `fill_out_form'", "/home/congressforms/congress-forms/app/helpers/form_fill_handler.rb:15:in `block in create_thread'"]",
run_at: "2014-04-07T10:49:05+00:00"
}
```

Get this when submitting Rand Pauls captcha

**Comment by Hainish** [comment]
I haven't gotten this.  Do you remember if you submitted the captcha more than a few minutes after it appeared?  This might be the cause.
Bill
